# Generated by Django 5.2.15 on 2026-06-21 03:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobViewEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonymous_session_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='anonymous session hash')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='viewed at')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='jobs.job')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_view_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'job view event',
                'verbose_name_plural': 'job view events',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['job', '-viewed_at'], name='analytics_j_job_id_264bd5_idx'), models.Index(fields=['job', 'user', '-viewed_at'], name='analytics_j_job_id_756f51_idx'), models.Index(fields=['job', 'anonymous_session_hash', '-viewed_at'], name='analytics_j_job_id_e83db6_idx')],
            },
        ),
    ]
