# Generated by Django 5.2.15 on 2026-06-21 03:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
                ('category', models.CharField(choices=[('roles_in_focus', 'Roles in focus'), ('hiring_outlook', 'Hiring outlook'), ('skills', 'Skills'), ('salary_guidance', 'Salary guidance'), ('other', 'Other')], default='other', max_length=32, verbose_name='category')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in the public list.', verbose_name='display order')),
                ('is_published', models.BooleanField(default=False, help_text='Only published insights are shown publicly.', verbose_name='published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'market insight',
                'verbose_name_plural': 'market insights',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
