# Generated by Django 5.2.15 on 2026-06-20 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.employers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='company name')),
                ('contact_person', models.CharField(max_length=150, verbose_name='contact person')),
                ('phone', models.CharField(max_length=40, verbose_name='phone')),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20, verbose_name='approval status')),
                ('approval_reason', models.TextField(blank=True, default='', verbose_name='approval reason')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('suspended_at', models.DateTimeField(blank=True, null=True, verbose_name='suspended at')),
                ('logo', models.FileField(blank=True, null=True, upload_to=apps.employers.models.logo_upload_path, verbose_name='logo')),
                ('company_summary', models.TextField(blank=True, default='', verbose_name='company summary')),
                ('website', models.URLField(blank=True, default='', verbose_name='website')),
                ('industry', models.CharField(blank=True, default='', max_length=120, verbose_name='industry')),
                ('company_size', models.CharField(blank=True, default='', max_length=60, verbose_name='company size')),
                ('company_location', models.CharField(blank=True, default='', max_length=150, verbose_name='company location')),
                ('culture_text', models.TextField(blank=True, default='', verbose_name='culture')),
                ('benefits_text', models.TextField(blank=True, default='', verbose_name='benefits')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_approvals', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'employer profile',
                'verbose_name_plural': 'employer profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
