"""Support-request workflow (spec §14.5, §15.7, §22.1).

Two write paths live here so views/admin stay thin and the rules sit in one
place:

* :func:`create_support_request` — public intake (guest OR candidate). It links
  the requester when authenticated, links the referenced job when one is given,
  and validates any attachment with the SAME engine as candidate resumes
  (extension allowlist + size cap + magic-byte sniff) before storing it under a
  private, opaque name. Reusing ``resume_service.validate_resume_upload`` means
  there is one validation policy, not two that can drift.

* :func:`change_status` — staff workflow transition. It updates ``status`` (and
  optionally ``assigned_to``) atomically and records exactly one audit entry, so
  the support queue has the same tamper-evident trail as other sensitive admin
  actions (audit via :func:`apps.audit.services.record_action`).
"""

from __future__ import annotations

from pathlib import PurePosixPath

from django.core.files.uploadedfile import UploadedFile
from django.db import transaction

from apps.audit.services import record_action
from apps.candidates.services.resume_service import validate_resume_upload
from apps.jobs.models import Job
from apps.support.models import SupportRequest, SupportStatus


def _safe_attachment_name(filename: str, ext: str) -> str:
    """Sanitise the client filename for display/download (never for storage)."""
    base = PurePosixPath(filename or "").name or f"attachment.{ext}"
    cleaned = "".join(ch for ch in base if ch.isprintable() and ch not in '\\/"\r\n\t')
    cleaned = cleaned.strip() or f"attachment.{ext}"
    return cleaned[:255]


@transaction.atomic
def create_support_request(
    *,
    user=None,
    job: Job | None = None,
    name: str,
    email: str,
    phone: str = "",
    category: str,
    message: str,
    attachment: UploadedFile | None = None,
) -> SupportRequest:
    """Create a support request, validating + privately storing any attachment.

    ``user`` is the authenticated requester (or ``None`` for a guest); ``job`` is
    the optional referenced listing. The attachment, if present, is validated by
    the shared resume engine and rejected (DRF ``ValidationError``, normalised
    envelope) before any row is written, so a bad upload never persists a request.
    """
    resume_original_name = ""
    if attachment is not None:
        ext = validate_resume_upload(attachment)
        resume_original_name = _safe_attachment_name(attachment.name, ext)

    request = SupportRequest(
        user=user,
        job=job,
        name=name,
        email=email,
        phone=phone or "",
        category=category,
        message=message,
        status=SupportStatus.NEW,
    )
    if attachment is not None:
        # The opaque server-side name is generated by the FileField's upload_to;
        # the client name only survives as display metadata.
        request.resume_file = attachment
        request.resume_original_name = resume_original_name
    request.save()
    return request


@transaction.atomic
def change_status(
    *,
    support_request: SupportRequest,
    new_status: str,
    actor,
    assigned_to=...,
) -> SupportRequest:
    """Transition a support request's status, recording one audit entry.

    Writes the new status (and ``assigned_to`` when provided — pass the sentinel
    default to leave assignment unchanged) and records ``support.status_changed``
    with the from/to values inside the same transaction, so a rollback drops the
    audit row too. ``new_status`` must be a valid ``SupportStatus`` value.
    """
    if new_status not in SupportStatus.values:
        raise ValueError(f"Invalid support status: {new_status!r}")

    old_status = support_request.status
    update_fields = ["status", "updated_at"]
    support_request.status = new_status

    metadata = {"from": old_status, "to": new_status}
    if assigned_to is not ...:
        support_request.assigned_to = assigned_to
        update_fields.append("assigned_to")
        metadata["assigned_to"] = str(assigned_to.pk) if assigned_to is not None else None

    support_request.save(update_fields=update_fields)

    record_action(
        actor=actor,
        action="support.status_changed",
        target=support_request,
        metadata=metadata,
    )
    return support_request
