# Generated by Django 5.2.15 on 2026-06-20 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='action')),
                ('target_type', models.CharField(blank=True, default='', max_length=100, verbose_name='target type')),
                ('target_id', models.CharField(blank=True, default='', max_length=64, verbose_name='target id')),
                ('metadata_json', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action; null if the actor was deleted or the system.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='audit_audit_target__2d648a_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx'), models.Index(fields=['-created_at'], name='audit_audit_created_6e540c_idx')],
            },
        ),
    ]
