# Generated by Django 5.2.15 on 2026-06-20 18:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobFitResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(verbose_name='score')),
                ('band', models.CharField(choices=[('strong', 'Strong match'), ('good', 'Good potential match'), ('partial', 'Partial match'), ('limited', 'Limited match')], max_length=20, verbose_name='band')),
                ('matched_json', models.JSONField(blank=True, default=list, verbose_name='matched reasons')),
                ('gaps_json', models.JSONField(blank=True, default=list, verbose_name='gap reasons')),
                ('unknown_json', models.JSONField(blank=True, default=list, verbose_name='unknown reasons')),
                ('rule_version', models.CharField(max_length=20, verbose_name='rule version')),
                ('ai_enabled', models.BooleanField(default=False, verbose_name='AI explanation enabled')),
                ('ai_provider', models.CharField(blank=True, default='', max_length=100, verbose_name='AI provider')),
                ('ai_model', models.CharField(blank=True, default='', max_length=100, verbose_name='AI model')),
                ('ai_explanation', models.TextField(blank=True, default='', verbose_name='explanation')),
                ('generated_at', models.DateTimeField(auto_now=True, verbose_name='generated at')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_fit_results', to='candidates.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_fit_results', to='jobs.job')),
            ],
            options={
                'verbose_name': 'job fit result',
                'verbose_name_plural': 'job fit results',
                'ordering': ['-generated_at'],
                'constraints': [models.UniqueConstraint(fields=('candidate', 'job'), name='uniq_jobfit_candidate_job')],
            },
        ),
    ]
