# Generated by Django 5.2.15 on 2026-06-20 15:20

import apps.candidates.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='full name')),
                ('phone', models.CharField(max_length=40, verbose_name='phone')),
                ('preferred_job_title', models.CharField(max_length=150, verbose_name='preferred job title')),
                ('preferred_location', models.CharField(blank=True, default='', max_length=150, verbose_name='preferred location')),
                ('preferred_employment_type', models.CharField(blank=True, default='', max_length=50, verbose_name='preferred employment type')),
                ('resume_file', models.FileField(blank=True, null=True, storage=apps.candidates.storage.private_resume_storage, upload_to=apps.candidates.storage.ResumeUploadTo(), verbose_name='resume file')),
                ('resume_original_name', models.CharField(blank=True, default='', max_length=255, verbose_name='resume original name')),
                ('resume_uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='resume uploaded at')),
                ('resume_parsing_status', models.CharField(choices=[('NONE', 'No resume'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='NONE', max_length=20, verbose_name='resume parsing status')),
                ('resume_extracted_keywords_json', models.JSONField(blank=True, default=list, verbose_name='resume extracted keywords')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'candidate profile',
                'verbose_name_plural': 'candidate profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
