# Generated by Django 5.2.15 on 2026-06-20 16:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0002_employerprofile_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True, verbose_name='slug')),
                ('source_type', models.CharField(choices=[('MHA_DIRECT', 'MHA direct'), ('EMPLOYER_PARTNER', 'Employer partner'), ('AFFILIATE_REFERRAL', 'Affiliate referral')], default='EMPLOYER_PARTNER', max_length=20, verbose_name='source type')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='location')),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full time'), ('PART_TIME', 'Part time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship'), ('TEMPORARY', 'Temporary')], default='FULL_TIME', max_length=20, verbose_name='employment type')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='salary minimum')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='salary maximum')),
                ('salary_currency', models.CharField(default='MYR', max_length=3, verbose_name='salary currency')),
                ('salary_period', models.CharField(choices=[('HOURLY', 'Per hour'), ('DAILY', 'Per day'), ('MONTHLY', 'Per month'), ('YEARLY', 'Per year')], default='MONTHLY', max_length=10, verbose_name='salary period')),
                ('salary_disclosed', models.BooleanField(default=False, verbose_name='salary disclosed')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('requirements', models.TextField(blank=True, default='', verbose_name='requirements')),
                ('application_deadline', models.DateField(blank=True, null=True, verbose_name='application deadline')),
                ('listing_language', models.CharField(choices=[('en', 'English'), ('zh-CN', 'Simplified Chinese')], default='en', max_length=10, verbose_name='listing language')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20, verbose_name='status')),
                ('is_mha_supported', models.BooleanField(default=False, verbose_name='MHA supported')),
                ('moderation_reason', models.TextField(blank=True, default='', verbose_name='moderation reason')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='employers.employerprofile')),
            ],
            options={
                'verbose_name': 'job',
                'verbose_name_plural': 'jobs',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500, verbose_name='question')),
                ('question_type', models.CharField(choices=[('SHORT_TEXT', 'Short text'), ('LONG_TEXT', 'Long text'), ('YES_NO', 'Yes / No'), ('SINGLE_CHOICE', 'Single choice'), ('NUMBER', 'Number')], default='SHORT_TEXT', max_length=20, verbose_name='question type')),
                ('is_required', models.BooleanField(default=True, verbose_name='required')),
                ('options_json', models.JSONField(blank=True, default=list, verbose_name='options')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_questions', to='jobs.job')),
            ],
            options={
                'verbose_name': 'screening question',
                'verbose_name_plural': 'screening questions',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', '-published_at'], name='jobs_job_status_a9561c_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['employer', 'status'], name='jobs_job_employe_9a6de3_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['employment_type'], name='jobs_job_employm_743f88_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['application_deadline'], name='jobs_job_applica_af0dc4_idx'),
        ),
        migrations.AddIndex(
            model_name='screeningquestion',
            index=models.Index(fields=['job', 'display_order'], name='jobs_screen_job_id_141268_idx'),
        ),
    ]
