# Generated by Django 5.2.15 on 2026-06-22 13:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0002_employerprofile_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=120, verbose_name='reviewer name')),
                ('reviewer_email', models.EmailField(max_length=254, verbose_name='reviewer email')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('title', models.CharField(blank=True, default='', max_length=150, verbose_name='title')),
                ('body', models.TextField(blank=True, default='', verbose_name='body')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='employers.employerprofile')),
            ],
            options={
                'verbose_name': 'company review',
                'verbose_name_plural': 'company reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployerReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='body')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_replies', to=settings.AUTH_USER_MODEL)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='reviews.companyreview')),
            ],
            options={
                'verbose_name': 'employer reply',
                'verbose_name_plural': 'employer replies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='companyreview',
            index=models.Index(fields=['employer', '-created_at'], name='reviews_com_employe_7571ed_idx'),
        ),
    ]
