# Generated by Django 5.2.15 on 2026-06-21 03:23

import apps.candidates.storage
import apps.support.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, default='', max_length=40, verbose_name='phone')),
                ('category', models.CharField(choices=[('JOB_APPLICATION', 'Job application help'), ('RESUME', 'Resume help'), ('CAREER_DIRECTION', 'Career direction'), ('APPLICATION_STATUS', 'Application status'), ('OTHER', 'Other')], default='OTHER', max_length=30, verbose_name='category')),
                ('message', models.TextField(verbose_name='message')),
                ('resume_file', models.FileField(blank=True, null=True, storage=apps.candidates.storage.PrivateResumeStorage(), upload_to=apps.support.storage.SupportAttachmentUploadTo(), verbose_name='attachment')),
                ('resume_original_name', models.CharField(blank=True, default='', max_length=255, verbose_name='attachment original name')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='NEW', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_requests', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests', to='jobs.job')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'support request',
                'verbose_name_plural': 'support requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='support_sup_status_2c5003_idx'), models.Index(fields=['user', '-created_at'], name='support_sup_user_id_bcb34a_idx')],
            },
        ),
    ]
